# Generated by Django 4.0.4 on 2022-04-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('style', models.CharField(choices=[('SC', 'Self-contain'), ('1RA', 'One room apartment'), ('2RA', 'Two room apartment'), ('3RA', 'Three room apartment'), ('4RA', 'Four room apartment')], max_length=3)),
                ('pictures', models.ImageField(upload_to='core/static/core/images')),
                ('price', models.PositiveIntegerField()),
                ('water', models.BooleanField(default=False)),
                ('spaces', models.PositiveIntegerField(default=1)),
                ('occupied', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
    ]
