# Generated by Django 4.0.4 on 2022-04-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='pictures',
            field=models.ImageField(upload_to='core/static/core/images'),
        ),
    ]
